services:
  - type: web
    name: fabric-production-tracker
    env: node
    buildCommand: npm install --no-audit --no-fund && npm run build
    startCommand: npm start
    plan: starter
    region: oregon
    branch: main
    buildFilter:
      paths:
      - client/**
      - server.js
      - package.json
      - build-for-render.js
      - routes/**
    envVars:
      - key: NODE_ENV
        value: production
      - key: NODE_OPTIONS
        value: --max-old-space-size=2048
      - key: GENERATE_SOURCEMAP
        value: false
      - key: DISABLE_ESLINT_PLUGIN
        value: true
      - key: CI
        value: false 
      - key: SKIP_PREFLIGHT_CHECK
        value: true
      - key: PORT
        value: 10000
    # Add environment variables for Firebase (will be set in Render dashboard)
    # FIREBASE_PROJECT_ID
    # FIREBASE_CLIENT_EMAIL  
    # FIREBASE_PRIVATE_KEY_ID
    # FIREBASE_PRIVATE_KEY
    # FIREBASE_CLIENT_ID
    # FIREBASE_CLIENT_CERT_URL 