services:
  - type: web
    name: fabric-production-tracker
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    plan: starter
    region: oregon
    branch: main
    envVars:
      - key: NODE_ENV
        value: production
      - key: NODE_OPTIONS
        value: --max-old-space-size=1024 